language: python

sudo: required
dist: xenial

python: "3.5"

services:
    - redis-server
    - mongodb

addons:
  apt:
    sources:
      - elasticsearch-2.x
      - mongodb-3.4-precise
    packages:
      - unixodbc
      - unixodbc-dev
      - freetds-dev
      - freetds-bin
      - tdsodbc
      - elasticsearch
      - mongodb-org-server

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - sudo apt-get purge elasticsearch -y
    - sudo apt-get install -y elasticsearch=2.4.6
    - nvm install 6.10
    - nvm use 6.10
    - node --version
    - npm install -g npm@3
    - npm install -g grunt-cli

install:
    - cd server && pip install -r dev-requirements.txt && cd ..
    - cd client && npm install && cd ..

before_script: >
    sudo sed -i 's\enabled: true\enabled: false\' /etc/mongod.conf
    && sudo service mongod restart
    && sudo service elasticsearch restart

script:
    - cd server && flake8 && cd ..
    - cd server && time behave ./features/ --format progress2 --logging-level ERROR && cd ..
    - cd server && time nosetests && cd ..
    - cd client && node --max_old_space_size=8192 `which grunt` build && cd ..
    - cd server && python manage.py users:create -u test -p test -e test@localhost --admin && cd ..

after_script:
    - rm .npm/*.lock
